services:
  consul-server1:
    image: hashicorp/consul:latest
    container_name: consul-server1
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -bind=0.0.0.0 -retry-join=consul-server2 -retry-join=consul-server3 -node=networking-service-1
    environment:
      - CONSUL_ALLOW_STALE_READS=true
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    volumes:
      - ./consul_config:/consul/config
    ports:
      - "8500:8500"
    networks:
      - yashua-network

  consul-server2:
    image: hashicorp/consul:latest
    container_name: consul-server2
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -bind=0.0.0.0 -retry-join=consul-server1 -retry-join=consul-server3 -node=networking-service-2
    environment:
      - CONSUL_ALLOW_STALE_READS=true
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    volumes:
      - ./consul_config:/consul/config
    networks:
      - yashua-network

  consul-server3:
    image: hashicorp/consul:latest
    container_name: consul-server3
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -bind=0.0.0.0 -retry-join=consul-server1 -retry-join=consul-server2 -node=networking-service-3
    environment:
      - CONSUL_ALLOW_STALE_READS=true
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    volumes:
      - ./consul_config:/consul/config
    networks:
      - yashua-network

networks:
  yashua-network:
    driver: bridge
    external: true

volumes:
  consul-data1:
  consul-data2:
  consul-data3: