services:
  consul-server1:
    image: hashicorp/consul:latest
    container_name: consul-server1
    command: agent -server -bootstrap-expect=3 -ui -client=0.0.0.0
    volumes:
      - consul-data1:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net1

  consul-server2:
    image: hashicorp/consul:latest
    container_name: consul-server2
    command: agent -server -retry-join=consul-server1
    volumes:
      - consul-data2:/consul/data
    networks:
      - consul-net1

  consul-server3:
    image: hashicorp/consul:latest
    container_name: consul-server3
    command: agent -server -retry-join=consul-server1
    volumes:
      - consul-data3:/consul/data
    networks:
      - consul-net1

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    command: agent -retry-join=consul-server1
    networks:
      - consul-net1

networks:
  consul-net1:
    name: consul-net
    external: true

volumes:
  consul-data1:
  consul-data2:
  consul-data3: